export const GodHOST = process.env.REACT_APP_GOD_API_HOST || ''
export const apiUrls = {
  login: GodHOST.concat('AuthenticationGod/Login'),
  createLanguage: GodHOST.concat('/LanguageGod/insert'),
  getAllLanguage: GodHOST.concat('/LanguageGod/GetAll'),
  deleteLanguage: GodHOST.concat('/LanguageGod/Delete'),
  updateLanguage: GodHOST.concat('/LanguageGod/Update'),
  province: GodHOST.concat('/ProvinceGod/GetAll'),
  provinceGetAll: GodHOST.concat('/ProvinceGod/GetAll'),
  cityGetByProvinceId: GodHOST.concat('/CityGod/GetByProvinceID'),
  insertUser: GodHOST.concat('/UserGod/Insert'),
  getAllUser: GodHOST.concat('/UserGod/GetAll'),
  deleteUser: GodHOST.concat('/UserGod/Delete'),
  createTag: GodHOST.concat('/TagsknowledgeGod/Insert'),
  getAllTags: GodHOST.concat('/TagsknowledgeGod/GetAll'),
  deleteTags: GodHOST.concat('/TagsknowledgeGod/Delete'),
  updateTags: GodHOST.concat('/TagsknowledgeGod/Update'),
  getTranslateTagId: GodHOST.concat('/TranslateTagsGod/GetAllByTagID'),
  insertTranslate: GodHOST.concat('/TranslateTagsGod/Insert'),
  updateTranslate: GodHOST.concat('/TranslateTagsGod/Update'),
  insertRol: GodHOST.concat('/RoleGod/Insert'),
  getAllRol: GodHOST.concat('/RoleGod/GetAllSP'),
  deleteRol: GodHOST.concat('/RoleGod/Delete'),
  updateRol: GodHOST.concat('/RoleGod/Update'),
  getByUserId: GodHOST.concat('/UserGod/GetByID'),
  updateUser: GodHOST.concat('/UserGod/Update'),
  userRoleInsert: GodHOST.concat('/UserRoleGod/Insert'),
  getAllRoutes: GodHOST.concat('/RouteStructureGod/GetAll'),
  getAllRoutesByType: GodHOST.concat('/RouteStructureGod/GetAllByTypeRoute'),
  createRoteStructure: GodHOST.concat('/RouteStructureGod/Insert'),
  deleteRoteStructure: GodHOST.concat('/RouteStructureGod/Delete'),
  getAllTagsTranslate: GodHOST.concat('/TagsknowledgeGod/GetAllTagsTranslate'),
  getByIdRouteStructure: GodHOST.concat('/RouteStructureGod/GetByID'),
  updateRouteStructure: GodHOST.concat('/RouteStructure/Update'),
  getAllCompany: GodHOST.concat('/CompanyInfoGod/GetAll'),
  insertCompany: GodHOST.concat('/CompanyInfoGod/Insert'),
  deleteCompany: GodHOST.concat('/CompanyInfoGod/Delete'),
  updateCompany: GodHOST.concat('/CompanyInfoGod/Update'),
  getCompanyById: GodHOST.concat('/CompanyInfoGod/GetByID'),
  getAllCompanySP: GodHOST.concat('/CompanyInfoGod/GetAllSP'),
  getAllServerConnections: GodHOST.concat('/ServerConnectionGod/GetAll'),
  insertServerConnections: GodHOST.concat('/ServerConnectionGod/Insert'),
  deleteServerConnections: GodHOST.concat('/ServerConnectionGod/Delete'),
  updateServerConnections: GodHOST.concat('/ServerConnectionGod/Update'),
  getServerConnectionsById: GodHOST.concat('/ServerConnectionGod/GetByID'),
  getAllRoutesByParent: GodHOST.concat('/RouteStructureGod/GetAllByParent'),

}
